-- Nesimi Campusu: teacher + subject + class assignments (2026)
-- Generated from live DB on 2026-04-14T08:23:26.325Z
-- Updated on 2026-04-14: added missing teachers Fatimə Məmmədli, Sara Həmidova, Sahibə Fərzəliyeva.

begin;

create temporary table tmp_nesimi_extra_teachers (
  teacher_id text primary key,
  teacher_name text not null,
  first_name text not null,
  last_name text not null,
  department_name text not null
) on commit drop;

insert into tmp_nesimi_extra_teachers (
  teacher_id,
  teacher_name,
  first_name,
  last_name,
  department_name
)
values
  ('nesimi-teacher-fatime-memmedli', 'Fatimə Məmmədli', 'Fatimə', 'Məmmədli', 'Riyaziyyat və məntiq'),
  ('nesimi-teacher-sahibe-ferzeliyeva', 'Sahibə Fərzəliyeva', 'Sahibə', 'Fərzəliyeva', 'Fizika kafedrası'),
  ('nesimi-teacher-sara-hemidova', 'Sara Həmidova', 'Sara', 'Həmidova', 'Riyaziyyat və məntiq');

insert into public.teachers (
  id,
  org_id,
  name,
  first_name,
  last_name,
  department_id,
  branch_id,
  branch_ids,
  teacher_category,
  deleted_at,
  archived_at
)
select
  t.teacher_id,
  'default',
  t.teacher_name,
  t.first_name,
  t.last_name,
  d.id,
  b.id,
  array[b.id],
  'standard'::public.teacher_category,
  null,
  null
from tmp_nesimi_extra_teachers t
join public.branches b
  on b.org_id = 'default'
 and b.id = 'ef0b6b5b-c54f-458a-819e-f15fbcb82096'
join public.departments d
  on d.org_id = 'default'
 and d.branch_id = b.id
 and d.name = t.department_name
on conflict (id) do update
set name = excluded.name,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    department_id = excluded.department_id,
    branch_id = excluded.branch_id,
    branch_ids = excluded.branch_ids,
    teacher_category = excluded.teacher_category,
    deleted_at = null,
    archived_at = null;

create temporary table tmp_nesimi_subjects (
  subject_id text primary key,
  subject_name text not null
) on commit drop;

insert into tmp_nesimi_subjects (subject_id, subject_name)
values
  ('nesimi-ta-subject-art-des-fduh1r', 'Art&Des'),
  ('nesimi-ta-subject-azerb-history-74gs6o', 'Azerb History'),
  ('nesimi-ta-subject-azerb-tarixi-yoraft', 'Azerb tarixi'),
  ('nesimi-ta-subject-azerb-dili-12jllg0', 'Azerb. dili'),
  ('nesimi-ta-subject-azerb-tarixi-15k8der', 'Azerb. tarixi'),
  ('nesimi-ta-subject-biologiya-10gq3x1', 'Biologiya'),
  ('nesimi-ta-subject-biology-prcrrx', 'Biology'),
  ('nesimi-ta-subject-biznes-wwxosp', 'Biznes'),
  ('nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm', 'Cam Checkpoint Exam'),
  ('nesimi-ta-subject-chemistry-18gbog4', 'Chemistry'),
  ('nesimi-ta-subject-chess-12qs4g', 'Chess'),
  ('nesimi-ta-subject-cografiya-1spqms5', 'Cografiya'),
  ('nesimi-ta-subject-computing-a31st0', 'Computing'),
  ('nesimi-ta-subject-cre-essay-wr-14l9dvq', 'Cre. Essay Wr'),
  ('nesimi-ta-subject-deyerler-ks2slw', 'Deyerler'),
  ('nesimi-ta-subject-drama-13gvgn', 'Drama'),
  ('nesimi-ta-subject-edebiyyat-68fxgg', 'Edebiyyat'),
  ('nesimi-ta-subject-el-literature-1fu4ys0', 'EL&Literature'),
  ('nesimi-ta-subject-ferdi-inkisaf-gm4yq5', 'Ferdi inkisaf'),
  ('nesimi-ta-subject-fizika-yt42so', 'Fizika'),
  ('nesimi-ta-subject-fiziki-t-1umx1ms', 'Fiziki t'),
  ('nesimi-ta-subject-geography-1hifwbg', 'Geography'),
  ('nesimi-ta-subject-german-z7thnq', 'German'),
  ('nesimi-ta-subject-glob-pers-1shiue8', 'Glob. Pers'),
  ('nesimi-ta-subject-grammar-w5y7if', 'Grammar'),
  ('nesimi-ta-subject-heyat-bilgisi-e01q30', 'Heyat bilgisi'),
  ('nesimi-ta-subject-history-16uypo4', 'History'),
  ('nesimi-ta-subject-info-suni-int-12tk6nq', 'Info / Süni int'),
  ('nesimi-ta-subject-kimya-175xx3', 'Kimya'),
  ('nesimi-ta-subject-lang-arts-1ugam6o', 'Lang. Arts'),
  ('nesimi-ta-subject-library-time-18hvyvm', 'Library Time'),
  ('nesimi-ta-subject-logics-11qcfsl', 'Logics'),
  ('nesimi-ta-subject-logics-math-aax0tg', 'Logics (Math)'),
  ('nesimi-ta-subject-math-1f8rs', 'Math'),
  ('nesimi-ta-subject-mentiq-1220tgm', 'Mentiq'),
  ('nesimi-ta-subject-music-18hb0l', 'Music'),
  ('nesimi-ta-subject-musiqi-12awhx2', 'Musiqi'),
  ('nesimi-ta-subject-mutalie-saati-136pxej', 'Mutalie saati'),
  ('nesimi-ta-subject-o-turk-tarixi-lww6cz', 'O. türk tarixi'),
  ('nesimi-ta-subject-phsce-19b9q5', 'PHSCE'),
  ('nesimi-ta-subject-physics-hu58vb', 'Physics'),
  ('nesimi-ta-subject-ritorika-1im00db', 'Ritorika'),
  ('nesimi-ta-subject-riyaziyyat-2wc8rl', 'Riyaziyyat'),
  ('nesimi-ta-subject-robotics-1r4hqfj', 'Robotics'),
  ('nesimi-ta-subject-rus-dili-fyoy2a', 'Rus dili'),
  ('nesimi-ta-subject-sahmat-14tze5i', 'Sahmat'),
  ('nesimi-ta-subject-science-1n92fyc', 'Science'),
  ('nesimi-ta-subject-steamlab-10coeal', 'STEAMlab'),
  ('nesimi-ta-subject-tebiet-15d4a4n', 'Tebiet'),
  ('nesimi-ta-subject-techno-steam-1q7qtqw', 'Techno/STEAM'),
  ('nesimi-ta-subject-tedqiqat-19zvvax', 'Tedqiqat'),
  ('nesimi-ta-subject-texno-steam-pvqakn', 'Texno./STEAM'),
  ('nesimi-ta-subject-tesviri-i-eq1t9x', 'Tesviri i'),
  ('nesimi-ta-subject-umumi-tarix-1rp0jh0', 'Ümumi tarix'),
  ('nesimi-ta-subject-wellbeing-ujqw7l', 'Wellbeing');

delete from public.teaching_assignments
where org_id = 'default'
  and branch_id = 'ef0b6b5b-c54f-458a-819e-f15fbcb82096'
  and year = 2026
  and (subject_id = 'nesimi-subject-sinif-sesverme-2026' or subject_id like 'nesimi-ta-subject-%');

delete from public.subjects
where id = 'nesimi-subject-sinif-sesverme-2026'
   or id like 'nesimi-ta-subject-%';

insert into public.subjects (id, org_id, name, code, deleted_at, archived_at)
select
  s.subject_id,
  'default',
  s.subject_name,
  null,
  null,
  null
from tmp_nesimi_subjects s
on conflict (id) do update
set name = excluded.name,
    code = excluded.code,
    deleted_at = null,
    archived_at = null;

create temporary table tmp_nesimi_assignments (
  teacher_id text not null,
  class_code text not null,
  class_level text not null,
  subject_id text not null
) on commit drop;

insert into tmp_nesimi_assignments (teacher_id, class_code, class_level, subject_id)
values
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '6A4', '6', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '6A4', '6', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A1', '8', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A1', '8', 'nesimi-ta-subject-o-turk-tarixi-lww6cz'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A1', '8', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A3', '8', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A3', '8', 'nesimi-ta-subject-o-turk-tarixi-lww6cz'),
  ('nesimi-teacher-afet-kazimova-zakir-qizi', '8A3', '8', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-aida-mamedova-xxx', '1R1', '1', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-aida-mamedova-xxx', '1R1', '1', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aida-mamedova-xxx', '1R1', '1', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-aida-mamedova-xxx', '4R2', '4', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-amalya-semedova-sevdar-qizi', '3R1', '3', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-amalya-semedova-sevdar-qizi', '5E2', '5', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-amalya-semedova-sevdar-qizi', '7E1', '7', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-amalya-semedova-sevdar-qizi', '7E1', '7', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-amalya-semedova-sevdar-qizi', '7R1', '7', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-aydan-kerimli-etibar-qizi', '5R1', '5', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aydan-kerimli-etibar-qizi', '5R2', '5', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '1A1', '1', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '2A1', '2', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '3A1', '3', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '3A1', '3', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '3A1', '3', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '3A1', '3', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '4A1', '4', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '8A1', '8', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aynur-isgenderova-mehemmed-qizi', '8A3', '8', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aysel-memmedova-natiq-qizi', '2R1', '2', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-aysen-tariverdiyeva-elcin-qizi', '2A1', '2', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aysun-huseynova-huseyn-qizi', '5A1', '5', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aysun-huseynova-huseyn-qizi', '6A4', '6', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-aytac-bagirova-natiq-qizi', '4R1', '4', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-ayten-qasimova-qasim-qizi', '7A1', '7', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-ayten-qasimova-qasim-qizi', '7E1', '7', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-ayten-qasimova-qasim-qizi', '8A1', '8', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '1E1', '1', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '1E2', '1', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '1E3', '1', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '5A1', '5', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '5E2', '5', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '5R1', '5', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '5R2', '5', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '6A4', '6', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '6E1', '6', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '6R1', '6', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '7A1', '7', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '7R1', '7', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '8A3', '8', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '8R1', '8', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-balabek-eliyev-ruslan-oglu', '8R2', '8', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '1A1', '1', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '4E1', '4', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '4E1', '4', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '4E1', '4', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '4R1', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '5R2', '5', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '5R2', '5', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-ceyran-veliyeva-arif-qizi', '8R1', '8', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-dunya-selimova-edalet-qizi', '1A1', '1', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-dunya-selimova-edalet-qizi', '1E3', '1', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-dunya-selimova-edalet-qizi', '3A1', '3', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-dunya-selimova-edalet-qizi', '4A1', '4', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-dunya-selimova-edalet-qizi', '4A1', '4', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '1R1', '1', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '1R1', '1', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '2R3', '2', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '2R3', '2', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '2R3', '2', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-efsane-hesenova-mahir-qizi', '4R1', '4', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-elnara-memmedova-elcin-qizi', '3R1', '3', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '1E1', '1', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '1E2', '1', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '1E3', '1', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '2E1', '2', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '2E3', '2', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '3E1', '3', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-elsema-memmedova-afik-qizi', '3R1', '3', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '5A1', '5', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '5R1', '5', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '6R1', '6', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '6R3', '6', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '7R1', '7', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '8R1', '8', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-esmer-mehdiyeva-alim-qizi', '8R2', '8', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '2A1', '2', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '4R2', '4', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '4R2', '4', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '5A1', '5', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '5A1', '5', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '5A1', '5', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '5R2', '5', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '5R2', '5', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '6A1', '6', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '6E1', '6', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '7A1', '7', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-eliyeva-elsen-qizi', '8A1', '8', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '1E1', '1', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '1E1', '1', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '1E2', '1', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '4E1', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '4R1', '4', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '6E1', '6', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '8A1', '8', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '8A1', '8', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-fatime-hesenli-vekil-qizi', '8E1', '8', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-fidan-eliyeva-elxan-qizi', '4E1', '4', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-fidan-eliyeva-elxan-qizi', '5E2', '5', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '1E1', '1', 'nesimi-ta-subject-logics-11qcfsl'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '1E2', '1', 'nesimi-ta-subject-logics-11qcfsl'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '1E3', '1', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '2E1', '2', 'nesimi-ta-subject-logics-11qcfsl'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '2E1', '2', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-fidan-hesenova-memmed-qizi', '4E1', '4', 'nesimi-ta-subject-logics-11qcfsl'),
  ('nesimi-teacher-fidan-serdarova-rabil-qizi', '1R1', '1', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-fidan-serdarova-rabil-qizi', '2R3', '2', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-fidan-serdarova-rabil-qizi', '3R1', '3', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-fidan-serdarova-rabil-qizi', '4R1', '4', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-fidan-zerbeliyeva-aslan-qizi', '1E2', '1', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-fidan-zerbeliyeva-aslan-qizi', '1E2', '1', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-fidan-zerbeliyeva-aslan-qizi', '1E2', '1', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-fidan-zerbeliyeva-aslan-qizi', '1E2', '1', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-fidan-zerbeliyeva-aslan-qizi', '2A1', '2', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '3A1', '3', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '5R2', '5', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '6A4', '6', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '6R1', '6', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '6R1', '6', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '7R1', '7', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '7R1', '7', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-gunay-ehmed-zade-silduz-qizi', '7R1', '7', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '1A1', '1', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '1E1', '1', 'nesimi-ta-subject-music-18hb0l'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '1E1', '1', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '1E3', '1', 'nesimi-ta-subject-music-18hb0l'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '1R1', '1', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '2A1', '2', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '2E1', '2', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '2E3', '2', 'nesimi-ta-subject-music-18hb0l'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '3A1', '3', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '3R1', '3', 'nesimi-ta-subject-music-18hb0l'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '4A1', '4', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '4R1', '4', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '5A1', '5', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '5E2', '5', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '5R1', '5', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '6E1', '6', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-ismayilova-mahir-qizi', '8E1', '8', 'nesimi-ta-subject-musiqi-12awhx2'),
  ('nesimi-teacher-gunay-mahmudova-mukayil-qizi', '4E1', '4', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-gunay-mahmudova-mukayil-qizi', '4E1', '4', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-gunay-mahmudova-mukayil-qizi', '4E1', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-gunay-mahmudova-mukayil-qizi', '4E3', '4', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-gunay-mahmudova-mukayil-qizi', '4E3', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-gunay-nagiyeva-namikovna', '5A1', '5', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-gunay-nagiyeva-namikovna', '5A1', '5', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '1A1', '1', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '1E3', '1', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '1R1', '1', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '2A1', '2', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '2E1', '2', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '2R3', '2', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '3A1', '3', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '3R1', '3', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '4A1', '4', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '4E1', '4', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunduz-bayramov-ibrahim-oglu', '4R1', '4', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-gunel-abbasova-ziyeddin-qizi', '7A1', '7', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-gunel-abbasova-ziyeddin-qizi', '7E1', '7', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-gunel-abbasova-ziyeddin-qizi', '8A1', '8', 'nesimi-ta-subject-biologiya-10gq3x1'),
  ('nesimi-teacher-gunel-haciyeva-vahid-qizi', '1E1', '1', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-gunel-haciyeva-vahid-qizi', '1E2', '1', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-gunel-haciyeva-vahid-qizi', '2E3', '2', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-gunel-haciyeva-vahid-qizi', '2E3', '2', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-gunel-haciyeva-vahid-qizi', '2E3', '2', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-gunel-memmedli-sadiq-qizi', '2E3', '2', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-gunel-memmedli-sadiq-qizi', '2E3', '2', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-gunel-memmedli-sadiq-qizi', '3E1', '3', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-gunel-memmedli-sadiq-qizi', '3E1', '3', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '1E1', '1', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '1E2', '1', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '1E3', '1', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '2E1', '2', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '2E3', '2', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '3E1', '3', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '4E1', '4', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '5E2', '5', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '6E1', '6', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '7E1', '7', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xatire-ehmedzade-hicran-qizi', '8E1', '8', 'nesimi-ta-subject-german-z7thnq'),
  ('nesimi-teacher-xedice-sirinzade-sehriyar-qizi', '1A1', '1', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xedice-sirinzade-sehriyar-qizi', '1A1', '1', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-xedice-sirinzade-sehriyar-qizi', '2A1', '2', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xedice-sirinzade-sehriyar-qizi', '2A1', '2', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-xedice-sirinzade-sehriyar-qizi', '2A1', '2', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '1R1', '1', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '1R1', '1', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '2A1', '2', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '2A1', '2', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '2R3', '2', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '3R1', '3', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '4E1', '4', 'nesimi-ta-subject-deyerler-ks2slw'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '4R1', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '4R2', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '5E2', '5', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-xumar-mustafayeva-mahir-qizi', '7E1', '7', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '1A1', '1', 'nesimi-ta-subject-tesviri-i-eq1t9x'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '1R1', '1', 'nesimi-ta-subject-tesviri-i-eq1t9x'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '2A1', '2', 'nesimi-ta-subject-tesviri-i-eq1t9x'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '3A1', '3', 'nesimi-ta-subject-tesviri-i-eq1t9x'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '4R1', '4', 'nesimi-ta-subject-tesviri-i-eq1t9x'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '7E1', '7', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-ilahe-ehmedova-firuz-qizi', '8E1', '8', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '1E1', '1', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '1E2', '1', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '2E1', '2', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '2E3', '2', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '3E1', '3', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '4E1', '4', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '5E2', '5', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '6E1', '6', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '7E1', '7', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-azadova-elixan-qizi', '8E1', '8', 'nesimi-ta-subject-computing-a31st0'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '1A1', '1', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '1R1', '1', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '2A1', '2', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '2R3', '2', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '3A1', '3', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '4A1', '4', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-kerimova-azad-qizi', '4R1', '4', 'nesimi-ta-subject-drama-13gvgn'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '4E3', '4', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '5E2', '5', 'nesimi-ta-subject-azerb-history-74gs6o'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '5E2', '5', 'nesimi-ta-subject-history-16uypo4'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '5R2', '5', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '6E1', '6', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '6E1', '6', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-irade-memmedova-mayil-qizi', '7A1', '7', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-kemale-esgerova-agabey', '2A1', '2', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '2R3', '2', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '4E3', '4', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '5R1', '5', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '5R2', '5', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '6E1', '6', 'nesimi-ta-subject-biology-prcrrx'),
  ('nesimi-teacher-kemale-esgerova-agabey', '6R3', '6', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '7E1', '7', 'nesimi-ta-subject-biology-prcrrx'),
  ('nesimi-teacher-kemale-esgerova-agabey', '7R1', '7', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-kemale-esgerova-agabey', '8E1', '8', 'nesimi-ta-subject-biology-prcrrx'),
  ('nesimi-teacher-konul-ismayilova-muzeffer-qizi', '3A1', '3', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-konul-ismayilova-muzeffer-qizi', '4A1', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-konul-ismayilova-muzeffer-qizi', '4A1', '4', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-konul-sariyeva-arif-qizi', '4R1', '4', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-konul-sariyeva-arif-qizi', '4R1', '4', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-konul-sariyeva-arif-qizi', '4R2', '4', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '5E2', '5', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '5E2', '5', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '6E1', '6', 'nesimi-ta-subject-physics-hu58vb'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '7E1', '7', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '7E1', '7', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '7E1', '7', 'nesimi-ta-subject-physics-hu58vb'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '8E1', '8', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-qendab-mahmudzade-adil-qizi', '8E1', '8', 'nesimi-ta-subject-physics-hu58vb'),
  ('nesimi-teacher-lale-bayramova-elsad-qizi', '6A4', '6', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-lale-bayramova-elsad-qizi', '7A1', '7', 'nesimi-ta-subject-fizika-yt42so'),
  ('nesimi-teacher-lale-bayramova-elsad-qizi', '7E1', '7', 'nesimi-ta-subject-fizika-yt42so'),
  ('nesimi-teacher-lale-bayramova-elsad-qizi', '8A1', '8', 'nesimi-ta-subject-fizika-yt42so'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '1A1', '1', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '1E1', '1', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '1E1', '1', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '1E1', '1', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '1E2', '1', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '2A1', '2', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '3A1', '3', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '4A1', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '4A1', '4', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '4E3', '4', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '5E2', '5', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '6A1', '6', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '6E1', '6', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '6E1', '6', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '6R1', '6', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '7E1', '7', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '7E1', '7', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '7E1', '7', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-ehmedova-vaqifovna', '8A1', '8', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-leyla-kerimli-polad-qizi', '1A1', '1', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-leyla-kerimli-polad-qizi', '1A1', '1', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-leyla-kerimli-polad-qizi', '1A1', '1', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-leyla-rzayeva-arif-qizi', '6A4', '6', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-leyla-rzayeva-arif-qizi', '6A4', '6', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '5E2', '5', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '6E1', '6', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '7E1', '7', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8E1', '8', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8E1', '8', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8E1', '8', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8E1', '8', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8R1', '8', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-leyla-yusifli-huseyn-qizi', '8R1', '8', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '1A1', '1', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '2A1', '2', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '3A1', '3', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '4A1', '4', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '5A1', '5', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '6A1', '6', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '7A1', '7', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-mehriban-agazade-cingiz-qizi', '8A3', '8', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '2E1', '2', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '2E1', '2', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '3A1', '3', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '3E1', '3', 'nesimi-ta-subject-cam-checkpoint-exam-1eqjfwm'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '3E1', '3', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-nabat-eliyeva-rehim-qizi', '3E1', '3', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '1E1', '1', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '1E2', '1', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '2E1', '2', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '2E3', '2', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '4E1', '4', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '4E3', '4', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '4E3', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '5E2', '5', 'nesimi-ta-subject-el-literature-1fu4ys0'),
  ('nesimi-teacher-naciye-elizade-mahir-qizi', '7E1', '7', 'nesimi-ta-subject-el-literature-1fu4ys0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '5A1', '5', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '5R2', '5', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '6A4', '6', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '6R3', '6', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '7R1', '7', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-naile-hesenova-nadir-qizi', '8R1', '8', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '1E1', '1', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '1E2', '1', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '4E3', '4', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '5A1', '5', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '5E2', '5', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '5R2', '5', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '6A1', '6', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '6A4', '6', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '6R3', '6', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '7A1', '7', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '7E1', '7', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '8A1', '8', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '8E1', '8', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-namiq-quliyev-teyyar-oglu', '8R1', '8', 'nesimi-ta-subject-fiziki-t-1umx1ms'),
  ('nesimi-teacher-nazli-kara-xanlar-qizi', '1E1', '1', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-nazli-kara-xanlar-qizi', '1E2', '1', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-nazli-kara-xanlar-qizi', '2R3', '2', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nazli-kara-xanlar-qizi', '4A1', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nergiz-quliyeva-agaqulu-qizi', '8R1', '8', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '1E1', '1', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '1E3', '1', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '2E3', '2', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '3E1', '3', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '6E1', '6', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-nermin-cabbarli-huseyn-qizi', '7E1', '7', 'nesimi-ta-subject-library-time-18hvyvm'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '4E3', '4', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '4E3', '4', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '5E2', '5', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '5E2', '5', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '5E2', '5', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '5E2', '5', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '6A1', '6', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '6A4', '6', 'nesimi-ta-subject-azerb-dili-12jllg0'),
  ('nesimi-teacher-nermin-memmedli-natiq-qizi', '6E1', '6', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '5E2', '5', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '5E2', '5', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '6A1', '6', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '6A1', '6', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '7A1', '7', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '7A1', '7', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '8A1', '8', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-nesrin-cavadova-resadet-qizi', '8A1', '8', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-nezrin-huseynzade', '1E1', '1', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '1E2', '1', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '1E3', '1', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '2E1', '2', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '3E1', '3', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '4E1', '4', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nezrin-huseynzade', '7E1', '7', 'nesimi-ta-subject-robotics-1r4hqfj'),
  ('nesimi-teacher-nusabe-qayayeva-elyar-qizi', '8R1', '8', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-nusabe-qayayeva-elyar-qizi', '8R1', '8', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-nusabe-qayayeva-elyar-qizi', '8R2', '8', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '6A4', '6', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '6R1', '6', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '7E1', '7', 'nesimi-ta-subject-biznes-wwxosp'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '7R1', '7', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '8A1', '8', 'nesimi-ta-subject-biznes-wwxosp'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '8R1', '8', 'nesimi-ta-subject-biznes-wwxosp'),
  ('nesimi-teacher-raisa-siraliyeva-maksudovna', '8R1', '8', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-rena-abasova-ilqar-qizi', '1R1', '1', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '2E1', '2', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '2E3', '2', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '3E1', '3', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '4E1', '4', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '5E2', '5', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '6E1', '6', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '7E1', '7', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-resad-emirguneyev-seydulla-oglu', '8E1', '8', 'nesimi-ta-subject-techno-steam-1q7qtqw'),
  ('nesimi-teacher-rovsen-eliyev-isfendiyar-oglu', '4E3', '4', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-rovsen-eliyev-isfendiyar-oglu', '5E2', '5', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-rovsen-eliyev-isfendiyar-oglu', '5E2', '5', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-rovsen-eliyev-isfendiyar-oglu', '6A4', '6', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-rovsen-eliyev-isfendiyar-oglu', '6E1', '6', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-rufet-medetov-memmed-huseyn-oglu', '6A4', '6', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-rufet-medetov-memmed-huseyn-oglu', '6R3', '6', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-rufet-medetov-memmed-huseyn-oglu', '7R1', '7', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-rufet-medetov-memmed-huseyn-oglu', '8R1', '8', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '2R3', '2', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '3R1', '3', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '4R1', '4', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '4R2', '4', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '5R2', '5', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-ruhiye-tehmezli-sohrab-qizi', '5R2', '5', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '1R1', '1', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '3E1', '3', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '3E1', '3', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '4E1', '4', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '4R2', '4', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '6A4', '6', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-ruziyye-rehimova-fezayil-qizi', '7R1', '7', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '1A1', '1', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '1E2', '1', 'nesimi-ta-subject-chess-12qs4g'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '2A1', '2', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '2E1', '2', 'nesimi-ta-subject-chess-12qs4g'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '3A1', '3', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '4A1', '4', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '4E3', '4', 'nesimi-ta-subject-chess-12qs4g'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '4R1', '4', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '5A1', '5', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '5E2', '5', 'nesimi-ta-subject-chess-12qs4g'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '6A4', '6', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '6E1', '6', 'nesimi-ta-subject-chess-12qs4g'),
  ('nesimi-teacher-sahin-rehimov-elcin-oglu', '6R3', '6', 'nesimi-ta-subject-sahmat-14tze5i'),
  ('nesimi-teacher-samire-xelilova-ilqar-qizi', '5E2', '5', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '1A1', '1', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '2A1', '2', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '3A1', '3', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '3A1', '3', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '4A1', '4', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '4E3', '4', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '4E3', '4', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '5E2', '5', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '5E2', '5', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '6A1', '6', 'nesimi-ta-subject-tebiet-15d4a4n'),
  ('nesimi-teacher-seadet-memmedova-balayar-qizi', '6A1', '6', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-sema-avilova-fazil-qizi', '2A1', '2', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-sema-avilova-fazil-qizi', '2A1', '2', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-sema-avilova-fazil-qizi', '2R3', '2', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-sema-avilova-fazil-qizi', '3R1', '3', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-sema-avilova-fazil-qizi', '3R1', '3', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '3E1', '3', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '3E1', '3', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '4E3', '4', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '4E3', '4', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '6E1', '6', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-sevil-esrefli-firuz-qizi', '8E1', '8', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-sevinc-esedova-rufet-qizi', '7R1', '7', 'nesimi-ta-subject-kimya-175xx3'),
  ('nesimi-teacher-sevinc-esedova-rufet-qizi', '8R1', '8', 'nesimi-ta-subject-kimya-175xx3'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '5A1', '5', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '6A4', '6', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '6A4', '6', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '7E1', '7', 'nesimi-ta-subject-o-turk-tarixi-lww6cz'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '7R1', '7', 'nesimi-ta-subject-azerb-tarixi-15k8der'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8A1', '8', 'nesimi-ta-subject-azerb-tarixi-yoraft'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8A1', '8', 'nesimi-ta-subject-o-turk-tarixi-lww6cz'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8R1', '8', 'nesimi-ta-subject-azerb-tarixi-15k8der'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8R1', '8', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8R1', '8', 'nesimi-ta-subject-o-turk-tarixi-lww6cz'),
  ('nesimi-teacher-sukufe-huseynli-arif-qizi', '8R1', '8', 'nesimi-ta-subject-umumi-tarix-1rp0jh0'),
  ('nesimi-teacher-tunzale-cendirli-ali-qizi', '1E3', '1', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-tunzale-cendirli-ali-qizi', '1E3', '1', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-tunzale-cendirli-ali-qizi', '1E3', '1', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-tunzale-cendirli-ali-qizi', '2E3', '2', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-tunzale-cendirli-ali-qizi', '2E3', '2', 'nesimi-ta-subject-math-1f8rs'),
  ('nesimi-teacher-turkan-quliyeva-seyur-qizi', '7A1', '7', 'nesimi-ta-subject-kimya-175xx3'),
  ('nesimi-teacher-turkan-quliyeva-seyur-qizi', '7E1', '7', 'nesimi-ta-subject-kimya-175xx3'),
  ('nesimi-teacher-turkan-quliyeva-seyur-qizi', '8A1', '8', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-turkan-quliyeva-seyur-qizi', '8A1', '8', 'nesimi-ta-subject-kimya-175xx3'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '1A1', '1', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '4A1', '4', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '5E2', '5', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '5E2', '5', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '6A1', '6', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '6A4', '6', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '6E1', '6', 'nesimi-ta-subject-steamlab-10coeal'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '7A1', '7', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '7E1', '7', 'nesimi-ta-subject-steamlab-10coeal'),
  ('nesimi-teacher-ulfet-mustafayeva-efser-qizi', '8E1', '8', 'nesimi-ta-subject-steamlab-10coeal'),
  ('nesimi-teacher-ulker-muradova-namiq-qizi', '5E2', '5', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-ulker-muradova-namiq-qizi', '6A1', '6', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-ulker-muradova-namiq-qizi', '6E1', '6', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-ulker-muradova-namiq-qizi', '7A1', '7', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-ulker-muradova-namiq-qizi', '8A1', '8', 'nesimi-ta-subject-cografiya-1spqms5'),
  ('nesimi-teacher-ulviyye-nesirli-eli-qizi', '1A1', '1', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-ulviyye-nesirli-eli-qizi', '6E1', '6', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-ulviyye-nesirli-eli-qizi', '7A1', '7', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-ulviyye-nesirli-eli-qizi', '8A1', '8', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '4R1', '4', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '4R2', '4', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '5A1', '5', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '5R2', '5', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '6E1', '6', 'nesimi-ta-subject-chemistry-18gbog4'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '7E1', '7', 'nesimi-ta-subject-chemistry-18gbog4'),
  ('nesimi-teacher-vasif-huseynov-ramazan-oglu', '8E1', '8', 'nesimi-ta-subject-chemistry-18gbog4'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '1R1', '1', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '1R1', '1', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '2R1', '2', 'nesimi-ta-subject-info-suni-int-12tk6nq'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '2R1', '2', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '3R1', '3', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '4R1', '4', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '5A1', '5', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '6A4', '6', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '6R3', '6', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vefa-aliszade-telman-qizi', '7R1', '7', 'nesimi-ta-subject-texno-steam-pvqakn'),
  ('nesimi-teacher-vuqar-agayev-gulbala-oglu', '6R1', '6', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-vuqar-agayev-gulbala-oglu', '8R2', '8', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '1E1', '1', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '1E3', '1', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '2A1', '2', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '2E1', '2', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '2E1', '2', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '3E1', '3', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '3E1', '3', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '4E1', '4', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '5E2', '5', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zehra-elizade-zeka-qizi', '6E1', '6', 'nesimi-ta-subject-art-des-fduh1r'),
  ('nesimi-teacher-zekiyye-memmedova-nazim-qizi', '4E3', '4', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-zekiyye-memmedova-nazim-qizi', '4E3', '4', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-zekiyye-memmedova-nazim-qizi', '4E3', '4', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-zekiyye-memmedova-nazim-qizi', '5E2', '5', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-zekiyye-memmedova-nazim-qizi', '6A1', '6', 'nesimi-ta-subject-ritorika-1im00db'),
  ('nesimi-teacher-zenfira-pasayeva-bedreddin-qizi', '2A1', '2', 'nesimi-ta-subject-heyat-bilgisi-e01q30'),
  ('nesimi-teacher-zenfira-pasayeva-bedreddin-qizi', '2A1', '2', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-zenfira-pasayeva-bedreddin-qizi', '2A1', '2', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-zenfira-pasayeva-bedreddin-qizi', '3R1', '3', 'nesimi-ta-subject-riyaziyyat-2wc8rl'),
  ('nesimi-teacher-zenfira-pasayeva-bedreddin-qizi', '4R1', '4', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-zhala-shukurova-xxx', '1E3', '1', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-zhala-shukurova-xxx', '3E1', '3', 'nesimi-ta-subject-glob-pers-1shiue8'),
  ('nesimi-teacher-zhala-shukurova-xxx', '5A1', '5', 'nesimi-ta-subject-grammar-w5y7if'),
  ('nesimi-teacher-zhala-shukurova-xxx', '5A1', '5', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-zhala-shukurova-xxx', '6R3', '6', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-zhala-shukurova-xxx', '6R3', '6', 'nesimi-ta-subject-lang-arts-1ugam6o'),
  ('nesimi-teacher-zhala-shukurova-xxx', '6R3', '6', 'nesimi-ta-subject-mutalie-saati-136pxej'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '5E2', '5', 'nesimi-ta-subject-history-16uypo4'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '6E1', '6', 'nesimi-ta-subject-azerb-history-74gs6o'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '6E1', '6', 'nesimi-ta-subject-geography-1hifwbg'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '7E1', '7', 'nesimi-ta-subject-geography-1hifwbg'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '7E1', '7', 'nesimi-ta-subject-history-16uypo4'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '8E1', '8', 'nesimi-ta-subject-azerb-history-74gs6o'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '8E1', '8', 'nesimi-ta-subject-geography-1hifwbg'),
  ('nesimi-teacher-zinaida-musayeva-yasin-qizi', '8E1', '8', 'nesimi-ta-subject-history-16uypo4'),
  ('nesimi-teacher-ziver-resulova-nahid-qizi', '1R1', '1', 'nesimi-ta-subject-science-1n92fyc'),
  ('nesimi-teacher-ziver-resulova-nahid-qizi', '2E3', '2', 'nesimi-ta-subject-cre-essay-wr-14l9dvq'),
  ('nesimi-teacher-ziver-resulova-nahid-qizi', '4E1', '4', 'nesimi-ta-subject-phsce-19b9q5'),
  ('nesimi-teacher-ziver-resulova-nahid-qizi', '4E1', '4', 'nesimi-ta-subject-wellbeing-ujqw7l'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '6A4', '6', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '6A4', '6', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '6R1', '6', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '7R1', '7', 'nesimi-ta-subject-edebiyyat-68fxgg'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '7R1', '7', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '8R2', '8', 'nesimi-ta-subject-ferdi-inkisaf-gm4yq5'),
  ('nesimi-teacher-zohre-ceferova-esger-qizi', '8R2', '8', 'nesimi-ta-subject-rus-dili-fyoy2a'),
  ('nesimi-teacher-fatime-memmedli', '5A1', '5', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-fatime-memmedli', '5R2', '5', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-fatime-memmedli', '6R1', '6', 'nesimi-ta-subject-mentiq-1220tgm'),
  ('nesimi-teacher-sahibe-ferzeliyeva', '7R1', '7', 'nesimi-ta-subject-fizika-yt42so'),
  ('nesimi-teacher-sahibe-ferzeliyeva', '7R1', '7', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-sahibe-ferzeliyeva', '8R1', '8', 'nesimi-ta-subject-fizika-yt42so'),
  ('nesimi-teacher-sahibe-ferzeliyeva', '8R1', '8', 'nesimi-ta-subject-tedqiqat-19zvvax'),
  ('nesimi-teacher-sara-hemidova', '4E1', '4', 'nesimi-ta-subject-logics-math-aax0tg'),
  ('nesimi-teacher-sara-hemidova', '4E1', '4', 'nesimi-ta-subject-math-1f8rs');

insert into public.teaching_assignments (
  org_id,
  teacher_id,
  group_id,
  subject_id,
  branch_id,
  year,
  deleted_at,
  archived_at
)
select
  'default',
  a.teacher_id,
  g.id,
  a.subject_id,
  'ef0b6b5b-c54f-458a-819e-f15fbcb82096',
  2026,
  null,
  null
from tmp_nesimi_assignments a
join public.groups g
  on g.org_id = 'default'
 and g.branch_id = 'ef0b6b5b-c54f-458a-819e-f15fbcb82096'
 and g.name = a.class_code
 and g.deleted_at is null
join public.teachers t
  on t.id = a.teacher_id
 and t.org_id = 'default'
 and t.branch_id = 'ef0b6b5b-c54f-458a-819e-f15fbcb82096'
 and t.deleted_at is null
on conflict (org_id, teacher_id, group_id, subject_id, branch_id, year) do update
set deleted_at = null,
    archived_at = null;

commit;
